"""empty message

Revision ID: f365bba04f17
Revises: 
Create Date: 2020-01-31 20:11:58.208798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f365bba04f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinGenerator',
    sa.Column('serial_no', sa.Integer(length=12), nullable=False, autoincrement=True, unique=True),
    sa.Column('pin', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('serial_no'),
    sa.UniqueConstraint('pin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinGenerator')

    # ### end Alembic commands ###
